### ISSUE TITLE
No Such File or Directory Error in Some Courses.

### ISSUE THREAD

**Issue by sunnybhadana** [J3Patel/linkedin-learning-video-downloader#1]
Your script is working perfect :).
Thanks for this awesome script.
But in some courses, it shows No such File or Directory Error.
The script downloads some videos of that course but failed to download all. 
Here the SLUG of those courses. 
#'ai-the-linkedin-way-a-conversation-with-deepak-agarwal',
#'artificial-intelligence-for-project-managers',
#'learning-xai-explainable-artificial-intelligence'

**Comment by J3Patel** [comment]
@sunnybhadana issue is fixed can you check again
