### ISSUE TITLE
Could not Login.

### ISSUE THREAD

**Issue by MiChaelinzo** [J3Patel/linkedin-learning-video-downloader#14]
**I tried running it but got login error because of wrong credentials. Is the username beside your /in/ https://www.linkedin.com/in/username/  i typed the correct password, I also tried typing my email in the username section login.**
<img width="466" alt="learning" src="https://user-images.githubusercontent.com/68110223/91501292-fc79c580-e8cd-11ea-807d-fa5efcc7fd24.PNG">

**Comment by J3Patel** [comment]
you have to add your linked in email id and password

**Comment by MiChaelinzo** [comment]
> you have to add your linked in email id and password

example@gmail.com or example only?
