### ISSUE TITLE
Fatal error in launcher: Unable to create process using 

### ISSUE THREAD

**Issue by Shameera17** [J3Patel/linkedin-learning-video-downloader#15]
'"c:\users\shame\appdata\local\programs\python\python38-32\python.exe"  "C:\Users\Shame\AppData\Local\Programs\Python\Python38-32\Scripts\pip.exe" install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r .\requirements.txt': The system cannot find the file specified.

**Comment by J3Patel** [comment]
your working directory must be downloaded folder 'linkedin-learning-video-downloader' where requirement file exists
