### ISSUE TITLE
RuntimeError: [!] Could not login. Please check your credentials

### ISSUE THREAD

**Issue by AirIn19** [J3Patel/linkedin-learning-video-downloader#3]
Traceback (most recent call last):
  File "linkedin_learning.py", line 225, in <module>
    loop.run_until_complete(process())
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 209, in process
    await login(USERNAME, PASSWORD)
  File "linkedin_learning.py", line 95, in login
    raise RuntimeError("[!] Could not login. Please check your credentials")
RuntimeError: [!] Could not login. Please check your credentials

**Comment by linibensonjr** [comment]
I have this same issue

**Comment by margani** [comment]
This could be because two-step verification is turned on.

**Comment by linibensonjr** [comment]
@margani its wasnt even turned on at my end, so that is ruled out

**Comment by edwincm** [comment]
I'm having the same issue as well... anyone found a solution for this?

**Comment by XueqiYang** [comment]
> This could be because two-step verification is turned on.

The same thing to me, I also got this error even the two-step verification is turned off at my end.

**Comment by iyke4life** [comment]
I also got the same error message. Has anyone been able to fix this?

**Comment by capriciousduck** [comment]
Still, I get this issue.

**Comment by raf665** [comment]
did anyone found the solution for this problem???

**Comment by linibensonjr** [comment]
I guess not. But I found another downloader on gh that works pretty well using CLI

**Comment by capriciousduck** [comment]
> I guess not. But I found another downloader on gh that works pretty well using CLI

Which one?

**Comment by linibensonjr** [comment]
> I guess not. But I found another downloader on gh that works pretty well using CLI


I'm using mobile I could only quickly find my fork. Feel free to trace to the original repo
    https://github.com/linibensonjr/linkedin-course-downloader

**Comment by J3Patel** [comment]
@margani @AirIn19 Did you added email and password in config.py file?

**Comment by capriciousduck** [comment]
I too had the same issue earlier. I found out that the error occurs due to an IP change. I created my account on my laptop but tried the download the course from a server located in Finland. I installed xfce4 and firefox on my server and logged in to my LinkedIn account and then the script worked.
