### ISSUE TITLE
I am getting ERROR: Package u'aiohttp' requires a different Python: 2.7.16 not in '>=3.4.2' 

### ISSUE THREAD

**Issue by nomulas** [J3Patel/linkedin-learning-video-downloader#4]
Hi There I am getting 

ERROR: Package u'aiohttp' requires a different Python: 2.7.16 not in '>=3.4.2'

Can you please help.

**Comment by thachnv92** [comment]
You must run:
pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r .\requirements.txt

Or:
pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org aiohttp
pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org lxml
